# Generated by Django 5.1.1 on 2025-02-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='updated_medications',
            field=models.ManyToManyField(blank=True, related_name='appointment_updates', to='prescriptions.medication'),
        ),
    ]
